global:
  scrape_interval:     2s
  evaluation_interval: 2s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.1.12:3000']
